name: Evim APK Olustur

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sunucu Hatasini Atlat (Freetype Manuel Indirme)
        run: |
          mkdir -p .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/packages/freetype
          curl -L -o .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/packages/freetype/freetype-2.14.1.tar.gz https://downloads.sourceforge.net/project/freetype/freetype2/2.14.1/freetype-2.14.1.tar.gz

      - name: APK derle (resmi Kivy Buildozer Docker imaji ile)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostcwd \
            -e PIP_CONSTRAINT=/home/user/hostcwd/pip-constraints.txt \
            kivy/buildozer android debug

      - name: APK'yi indirilebilir yap
        uses: actions/upload-artifact@v4
        with:
          name: Evim-APK
          path: bin/*.apk
